# Time (in minutes) from the beginning of the day to turn on the strip
normal-time = 360

# An alternate normal-time for saturday
saturday-time = 420

# An alternate normal-time for saturday
sunday-time = 420

# Time (in minutes) to keep the strip on post normal-time
ramp-up-time = 90

# Time (in minutes) to keep the strip on post ramp-up
keep-on-time = 90

# An optional noise function to apply to the LED strip
# 0 / Unset disables this feature
# 1 - Random noise on all channels
# 2 - Sinusoidial noise on overall brightness (TODO)
# 3 - Cloud like (perlin) noise on overall brightness (TODO)
noise-type = 1

# Intensity of the above noise function freom 0 to 255
noise-intensity = 20

# Line fade amount, as ohm's law does its thing the voltage
# supplied to the leds will inevitably drop as the distance
# from the voltage source increases, for most LEDs this leads
# to a *somewhat* linear dip in brightness. This value is a
# fine adjustment to compensate for this effect
#
# A value of 64 here (config.c FINE_ADJ_MULTIPLIER) will drop
# the LED brightness by one brightness step per LED
#
# This is applied after the noise function
line-fade = 80

# Since people perceive higher spectrums of light at higher
# intensities, this makes the white perceived normally
#
# A simple 1x green 2x blue ratio is a good start
#
# This is applied after line fade
rgb-correct = 0x904800

# Overall LED strip brightness from 0 to 255
#
# This is applied as the final step
brightness = 255

# Logging verbosity
# 0 - Information only
# 1 - Verbose
# 2 - Debug
verbosity = 0
